# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.CharField(default='', max_length=20, verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='.', max_length=30, verbose_name='phone'),
        ),
    ]
