# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(max_length=600),
        ),
    ]
